# Generated by Django 3.1 on 2020-10-23 21:16

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    Individual = apps.get_model('fms_core', 'Individual')
    for individual in Individual.objects.all():
        individual.uuid = uuid.uuid4()
        individual.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0007_v2_3_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(create_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='individual',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
        )
    ]
