# Generated by Django 3.1 on 2020-10-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0008_individual_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='father',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='mother',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='individual',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
