# Generated by Django 3.1 on 2020-10-23 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0009_auto_20201023_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='id',
            field=models.CharField(help_text='Unique identifier for the individual.', max_length=200),
        ),
        migrations.AlterField(
            model_name='individual',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
