# Generated by Django 3.1 on 2021-01-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0010_v2_6_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='label',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='individual',
            name='cohort',
            field=models.CharField(blank=True, help_text='Name to group some individuals in a specific study.', max_length=200),
        ),
    ]
