# Generated by Django 3.1 on 2020-10-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0010_auto_20201023_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='father',
            new_name='father_old',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='mother',
            new_name='mother_old',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='individual',
            new_name='individual_old',
        ),
    ]
