# Generated by Django 3.1 on 2021-01-27 21:41

from django.db import migrations, models
from django.db.models import F
from fms_core.models import Sample
import django.utils.timezone


def update_creation_date_with_reception_date(apps, schema_editor):
    Sample.objects.all().update(creation_date=F('reception_date'))

class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0011_v3_0_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the sample reception or extraction.'),
        ),
        migrations.RunPython(
            update_creation_date_with_reception_date,
            migrations.RunPython.noop
        ),
    ]
