# Generated by Django 3.1 on 2020-10-23 21:41

from django.db import migrations, models
import django.db.models.deletion


def copy_individual_uuid(apps, schema_editor):
    Sample = apps.get_model('fms_core', 'Sample')
    Individual = apps.get_model('fms_core', 'Individual')
    sample_individual_uuid = Individual.objects.filter(id=models.OuterRef('individual_old')).values_list('uuid')[:1]
    Sample.objects.update(individual=models.Subquery(sample_individual_uuid))

    father_individual_uuid = Individual.objects.filter(id=models.OuterRef('father_old')).values_list('uuid')[:1]
    Individual.objects.update(father=models.Subquery(father_individual_uuid))

    mother_individual_uuid = Individual.objects.filter(id=models.OuterRef('mother_old')).values_list('uuid')[:1]
    Individual.objects.update(mother=models.Subquery(mother_individual_uuid))


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0011_auto_20201023_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='father',
            field=models.ForeignKey(blank=True, help_text='Father of the individual.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='father_of', to='fms_core.individual'),
        ),
        migrations.AddField(
            model_name='individual',
            name='mother',
            field=models.ForeignKey(blank=True, help_text='Mother of the individual.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother_of', to='fms_core.individual'),
        ),
        migrations.AddField(
            model_name='sample',
            name='individual',
            field=models.ForeignKey(help_text='Individual associated with the sample.', null=True, on_delete=django.db.models.deletion.PROTECT, to='fms_core.individual'),
        ),
        migrations.RunPython(
            copy_individual_uuid,
            reverse_code=migrations.RunPython.noop
        ),
    ]
