# Generated by Django 3.1 on 2020-10-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0012_auto_20201023_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='father_old',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='mother_old',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='individual_old',
        ),
    ]
