# Generated by Django 3.1 on 2020-10-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_core', '0013_auto_20201023_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='id',
            field=models.CharField(help_text='Unique identifier for the individual.', max_length=200, unique=True),
        ),
    ]
