# Generated by Django 3.1 on 2021-02-17 22:15

from django.db import migrations, models
import django.db.models.deletion

from fms_core.models._constants import SAMPLE_KINDS

class Migration(migrations.Migration):
    def create_sample_kinds(apps, schema_editor):
        SampleKind = apps.get_model("fms_core", "SampleKind")
        for kind in SAMPLE_KINDS:
            SampleKind.objects.create(name=kind)

    def copy_samples_kinds(apps, schema_editor):
        Sample = apps.get_model("fms_core", "Sample")

        SampleKind = apps.get_model("fms_core", "SampleKind")
        sample_kind_ids_by_name = {sample_kind.name: sample_kind.id for sample_kind in SampleKind.objects.all()}

        for sample in Sample.objects.all():
            name = sample.biospecimen_type
            sample.sample_kind_id = sample_kind_ids_by_name[name]
            sample.save()

     #TODO: versions

    dependencies = [
        ('fms_core', '0013_v3_0_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Biological material collected from study subject during the conduct of a genomic study project.', max_length=200)),
                ('molecule_ontology_curie', models.CharField(blank=True, help_text='SO ontology term to describe an molecule, such as ‘SO:0000991’ (‘genomic_DNA’)', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_kind',
            field=models.ForeignKey(blank=True, null=True, help_text='Biological material collected from study subject during the conduct of a genomic study project.', on_delete=django.db.models.deletion.PROTECT, to='fms_core.samplekind'),
        ),
        migrations.RunPython(
            create_sample_kinds,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            copy_samples_kinds,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='sample',
            name='biospecimen_type',
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_kind',
            field=models.ForeignKey(
                help_text='Biological material collected from study subject during the conduct of a genomic study project.',
                on_delete=django.db.models.deletion.PROTECT, to='fms_core.samplekind'),
        ),
        migrations.AlterField(
            model_name='samplekind',
            name='name',
            field=models.CharField(
                help_text='Biological material collected from study subject during the conduct of a genomic study project.',
                max_length=200, unique=True),
        ),
    ]
