__all__ = ["BARCODE_NAME_FIELD_LENGTH",
           "TEMPORARY_RENAME_SUFFIX"]

BARCODE_NAME_FIELD_LENGTH = 200
TEMPORARY_RENAME_SUFFIX = "$"


SAMPLE_KINDS = ['DNA', 'RNA', 'BLOOD', 'CELLS', 'EXPECTORATION', 'GARGLE', 'PLASMA', 'SALIVA', 'SWAB']